- README.md
O [Peixe Babel](https://www.youtube.com/user/CanalPeixeBabelt) é um canal formado por Mila Laranjeira, professora do COLTEC/UFMG, e Vivi Mota, também professora no COLTEC/UFMG.
Elas falam sobre ciência e tecnologia de uma forma muito boa de se acompanhar, fazem bate papos muito interessantes.
> Sugestão de canal - Peixe Babel

- README.md
Adicionado o canal 'Punk do DevOps', a organização 'PrograMaria' e o podcast 'PodProgramar'.
> Adicionando referências.

- README.md
Adicionei o canal " E ai, Carla!" como ultimo da lista.
O canal é sobre  Inteligência Artificial, programação, ética, diversidade, pesquisa.
> Add canal E,ai Carla! canal de IA

- README.md
Adicionei, na última posição da lista, o canal da PACHICodes na Twitch.
> added twitch channel PACHICodes

- README.md
Adicionado o perfil do Twitch da nomadCodeMist.
> nomadCodeMist

- README.md
Add Canal da Liara Programadora
> Add Liara Programadora

- README.md
Adicionado os canais de Liara Programadora e Nina da Hora
> Adicionado 2 canais de mulheres no Youtube.

- README.md
Canal no youtube Coding Blonde
> Add canal Coding Blonde

- README.md
Adicionando os canais das comunidades TheFemTech, QaLadies e SysAdminas
> Add comunidades

- README.md
Adicionado canais Laboratório da Julia, PyLadies Recife, Girls Support Girls e WiMLDS SP.
> Adicionado 4 canais do youtube.

- README.md
Adicionando novo canal e peço desculpas por ter dado o PR com um canal que já existia, não havia visto. >.<
> Adicionado Female Tech Leaders

- README.md
Organizei por ordem alfabética os tópicos e adicionei algumas mulheres live coders :smiley:
> Organização em ordem alfabética e adição de live coders

- README.md
Adicionando o canal do Pyladies Brasil =)
> Adicionando Pyladies Brasil

- README.md
> Adicionada seção para podcasts (#40)

- README.md
Adicionei a Ca Byte, youtuber iniciante na área da TI. Ela fala sobre assuntos relevantes para quem está começando na área também.
> Minha contribuição

- README.md
Added Angela Yu course for full stack web development.
> Angela Yu Course added

- README.md
Adcicionando nova youtuber ao repositório.
> Add new youtuber

- README.md
- Materiais da Lelemaine que me ajudaram muito como QA.
> QA resources

- README.md
add leitoraincomum na lista de streamers
> leitoraincomum

- README.md
adicionando um podcast que eu amo Start Coding uma iniciativa que apoia a inserção de mulheres na tecnologia e corrigindo o :brazil: em alguns títulos que estavam faltando
> Start coding <3

- README.md
Canais adicionados: shenetworks, Adriana Saty, Python Simplified, Simplificando Redes.
> Adicionei canais de youtube

- README.md
Adiciona o canal do YouTube da organização Manas Digitais, uma organização sem fins lucrativos que incentiva o ensino de tecnologia para crianças de escolas públicas e mulheres da região Amazônica
> Add Canal das Manas Digitais no README.md

- README.md
Adiciona o conteúdo da Simara Conceição: canal do youtube e podcast 'quero ser dev'.
> Feat: adiciona conteúdo da Simara Conceição - quero ser dev

- README.md
Eu recentemente encontrei essa youtuber e os videos dela tem me ajudado demais, acho mais que valido ela figurar nessa lista
> Add fernanda kipper
